# Default configuration. To achieve more accuracy in the compass, periodically
# regenerate:
#
#   rosrun grizzly_bringup calibrate_compass
#
# Grizzly will rotate slowly for 60 seconds and a new calibration will be
# generated.
#
mag_bias:
     x: 0.0
     y: 0.0
     z: 0.0
     radius: 0.0
